# Generated by Django 4.1.3 on 2022-11-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0002_alter_petition_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
