# Generated by Django 4.1.3 on 2022-11-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0003_alter_petition_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
