# Generated by Django 4.1.3 on 2022-11-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0006_petition_is_successful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='recipient',
            new_name='recipient_email',
        ),
        migrations.AddField(
            model_name='petition',
            name='recipient_name',
            field=models.CharField(default='Great Admin', max_length=100),
        ),
    ]
